// This file is automatically generated. Do not edit directly.
import { createFayzSupabaseClient, getFayzSupabaseClientOptional } from '@fayz-ai/saas';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

export const supabase = (
  getFayzSupabaseClientOptional() ??
  createFayzSupabaseClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY)
) as unknown as SupabaseClient<Database>;
